//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockerManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLocker
    {
        public string BadgeId { get; set; }
        public string LockerNumber { get; set; }
        public int TransactionId { get; set; }
        public int Id { get; set; }
        public int LockerID { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual Locker Locker { get; set; }
    }
}
