//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockerManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string BadgeId { get; set; }
        public string Name { get; set; }
        public string Locker { get; set; }
        public string Remark { get; set; }
        public string Superior { get; set; }
        public string SuperiorEmail { get; set; }
        public string Status { get; set; }
        public System.DateTime DateSubmit { get; set; }
        public string Category { get; set; }
        public string Department { get; set; }
    }
}
