//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockerManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GMDS
    {
        public int No { get; set; }
        public string Badge_ID { get; set; }
        public string Name { get; set; }
        public string Group { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public string Supervisor { get; set; }
        public string Area { get; set; }
        public string Password { get; set; }
        public string Superior_Email { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
    }
}
