//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockerManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.EmployeeLocker = new HashSet<EmployeeLocker>();
        }
    
        public int TransactionId { get; set; }
        public string BadgeId { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Area { get; set; }
        public string Site { get; set; }
        public int TransactionType { get; set; }
        public string FriendBadgeNumber { get; set; }
        public Nullable<int> LockerId { get; set; }
        public string LockerNumber { get; set; }
        public System.DateTime DateRequest { get; set; }
        public Nullable<System.DateTime> DateRelease { get; set; }
        public string Releaseby { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateTemporaryReturn { get; set; }
        public string Remark { get; set; }
        public string EmployeeGender { get; set; }
        public string Designation { get; set; }
        public string PIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLocker> EmployeeLocker { get; set; }
        public virtual Locker Locker { get; set; }
    }
}
